[project]
name = "backend"
version = "0.2.0"
description = "AriaBox ~"
requires-python = ">=3.14"
dependencies = [
    "flask==3.1.3",
    "mutagen==1.48.0",
    "waitress==3.0.2",
    "yutipy==5.3.4",
]

[build-system]
requires = ["uv_build>=0.11.21,<0.12"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "app"
module-root = ""

[project.scripts]
ariabox = "run:run_server"
